services:
  devhabit.api:
    image: devhabit.api
    build:
      context: .
      dockerfile: DevHabit.Api/Dockerfile
    ports:
      - "4000:8080"
      - "4001:8081"
    environment:
      # Seq
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.seq:5341/ingest/otlp
      # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
        
  devhabit.seq:
    image: datalust/seq
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: "test"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - "8080:80"
      - "5341:5341"
        
  devhabit.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - "18888:18888"

